### ISSUE TITLE
Add new CIVS vehicles like bmw , audi and Tesco vans we could some good rp with it[FEAT]

### ISSUE THREAD

**Issue by viiidal** [LondonsBlueLine/tracker#105]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jxckUK** [comment]
Unfortunately, its not part of our development plan to add civilian vehicles to the game. The difficulty is the following:

- These vehicles take up valuable memory allocations that could be otherwise spent on emergency service vehicles.
- When replacing vehicles you always run the risk of adding items that don't fit the handling and become a little whacky.
- Adding these vehicles would make CIV stand out a lot more, while this might sound good for you it makes it harder for CIVs to blend in with AI.
