### ISSUE TITLE
Satisfactory VC

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#171]
Perhaps change the Satisfactory text and voice chats to ready or not as this is a game that more people have and is more needing of its own channel?

**Comment by CalLBLRP** [comment]
**Suggestion Partially Accepted**

Your suggestion has been partially accepted. We have decided to accept a text channel named (other-games).

The voice chat part of your suggestion has been denied. This is due to the fact we have 2 other games channels which should be utilised. We feel that we do not need more channels as there are a reasonable amount as of right now.

Thanks for your suggestion,
Cal.
