### ISSUE TITLE
LFB recommendations and asset collection

### ISSUE THREAD

**Issue by viiidal** [LondonsBlueLine/tracker#185]
Any chance of getting a throwline added for water rescue?
https://unionmods.com/?p=viewfile&file=326 Bronze Command LFB Vehicle 
https://unionmods.com/?p=viewfile&file=375 Bronze Command LFB 
https://unionmods.com/?p=viewfile&file=480 Bronze Command LFB
https://unionmods.com/?p=viewfile&file=167 Bronze Command LFB

**Comment by Dale1987** [comment]
Will get onto adding these once we have finished with ELS i believe the top 3 are already in game just not in a a garage at the moment

**Comment by jxckUK** [comment]
Technical rescue unit, for water rescues / line rescues from height.

option for an OIC tabard so points of contact for each service are identifiable on scene.

Option to change uniform out-with the fire station, perhaps an option can be available from one of the lockers or from the boot of a service vehicle?

**Comment by CalLBLRP** [comment]
Hello @viiidal, 

Thank you for your LFB vehicle suggestion. Unfortunately, we have attempted to work with the Land Rover Discovery 4 (Heathrow Airport). This has failed Quality Check (QC) so we are unable to proceed with this. 

The other vehicles have been denied due to the quality/lack of permission seeking.
