### ISSUE TITLE
SRCT X5

### ISSUE THREAD

**Issue by jxckUK** [LondonsBlueLine/tracker#209]
_## Issue created anonymously for a user ##_
Possbile X5 for SRCT  https://unionmods.com/?p=viewfile&file=624

**Comment by JamStonedScones** [comment]
Love it!

**Comment by CalLBLRP** [comment]
**Suggestion Denied** 
Thank you for your suggestion. Unfortunately, your suggestion has been denied by MPS Gold Command and the Dev Team. The reason is that SRCT also known as Raptor, do not own x5s especially unmarked x5s. They primarily use BMW 330d.

Keep the suggestions coming! 

Thanks,
MPS Gold Command and Development Team.
