### ISSUE TITLE
Multiple vehicle requests

### ISSUE THREAD

**Issue by MikeyDeann** [LondonsBlueLine/tracker#247]
If You Could Like Review The Vehicles And  See If they Are Good Enough To Come Into the Server.

https://unionmods.com/?p=viewfile&file=574

https://unionmods.com/?p=viewfile&file=373

https://unionmods.com/?p=viewfile&file=682

https://unionmods.com/?p=viewfile&file=587

https://unionmods.com/?p=viewfile&file=548

**Comment by jxckUK** [comment]
[CalLBLRP](https://github.com/CalLBLRP)

**Comment by CalLBLRP** [comment]
Good Evening @MikeyDeann, 

Thank you for your suggestions for LAS and MPS. Which also include with an NPAS vehicle. I will go ahead and look through these vehicles and speak with the relevant department heads if needed. However, most of the vehicles have been suggested before but before I give you a definite answer, I will make sure to review all them beforehand. 

- Cal.

**Comment by telboycafc** [comment]
where we at with these @CalLBLRP any pass QC or approved ?

**Comment by telboycafc** [comment]
I like the first link. 
second link is also nice, if its a better bike than we currently have, pointless having 2.
Third link, I'm hit and miss with. 
Fourth link, is a no for me, looks awful. 
5th link is a no for me also. 
Thats my opinion.

**Comment by CalLBLRP** [comment]
Hello @MikeyDeann, 

Thank you for your requests, all the vehicles that you have put in have been through the LAS Director but as Union Mods is currently having a slight issue. I am unable to view them again, however.. we have got them saved; everything a part from the BMW Series 1 will be denied The BMW will be a **Band A** vehicle. The other vehicles have been denied due to the fact  the quality of the vehicle(s) or unable to seek permission for them.

Keep your suggestions coming, they are indeed helpful!
