### ISSUE TITLE
Defib sticking to player

### ISSUE THREAD

**Issue by WolfRanger88** [LondonsBlueLine/tracker#324]
**Describe the bug**
Defib sticking to player after getting out of van specifically advance paramedic fiat ducato

**To Reproduce**
1. get uniform, armoury items ( defib, bag, armour)
2. Get Van
3. No items equipped, retrieve defib from van via eye
4. Put defib on floor
5. pick defib back up
6. try to put defib back in van with eye 
7. NOTE.....upon testing, it appears to only happen if using controller

**Expected behavior**
Defib to be put in van rather than more spawn and it remain stuck needing relog

**Comment by SplendidBrit** [comment]
This is due to a duplicated bind for the drop command. Initially, the same button do drop was bound to retrieve from the ambulance. The drop action occurs first as it's quicker and so you end up placing the defib at your feet and picking a new one from the ambulance so it appears to be stuck and duplicating. To fix this, you need to rebind "Place Defib", "Place Entonox", and "Place Oxygen" to prevent this from happening.

The preset bind has been changed but doesn't help current players as its a client side bind

**Comment by WolfRanger88** [comment]
Ok, its only defib that appears to have the issue for me rest are ok.
