### ISSUE TITLE
RTPC Cars to get speed boost

### ISSUE THREAD

**Issue by Fleggy123** [LondonsBlueLine/tracker#337]
can all the RTPC cars get a speed boost to the level of the new interceptor cars as we are struggling to keep up with Civ Rp pursuits due to the cars maxing out at 99-105

**Comment by CalLBLRP** [comment]
Hi There @Fleggy123, 

The reason Interceptor vehicles are at the handling line that it has now is because Interceptor vehicles are supposed to be that speed. If we up the speed of **all** the vehicles to the Interceptor speed then that would leave Interceptor redundant and will be no use for it. 

I am going to be denying at this current time, I will look into a new handling line to increase the speed but it will not be the same/equivalent to Interceptor. 

Keep the suggestions coming!
