### ISSUE TITLE
SFC name change

### ISSUE THREAD

**Issue by char214** [LondonsBlueLine/tracker#391]
I am requesting a name change due to SFC being a role within mo19 and not a name of a division . SFC is also only a role silver command can access irl (met operations 19) or AFO or ARVO

**Comment by jxckUK** [comment]
I'm afraid this request is denied - This isn't necessarily an item we've chosen because its the exact set up in the real world. This is a name that was decided because its accessible for new players. 

We consistently tread a fine line between what is factual and what is suitable for the server being predominantly a game.

We are always challenged for the factual representation of the metropolitan police service and sometimes we agree with players assessments that things can be brought closer to reality.

In this instance "MO-19" is not an accessible name for people without the knowledge or understanding of real world policing.

However I also challenge the following statement: `not a name of a division`

This is incorrect, it is in-fact the accurate name of a division within MPS. The role "Strategic Firearms Commander" is indeed a silver command position but the two are distinctly different.

Feel free to review this FOI request which confirms we're using the correct name: https://www.met.police.uk/SysSiteAssets/foi-media/metropolitan-police/disclosure_2020/february_2020/information-rights-unit---organisational-structure-mo19
