### ISSUE TITLE
content helpers

### ISSUE THREAD

**Issue by char214** [LondonsBlueLine/tracker#416]
it would help me a lot and I'm sure the other content creators as well if we could have some sort of helpers that are simply in the content server to assist with videos or photographs.

**Comment by jxckUK** [comment]
This isn't a practical solution to the problem because we'll end up with too many people on a secondary server which doesn't have the resources to handle that load. Content creators should be assisting other content creators where possible, and we can look into ped spawning options for you to spawn in other non-player peds if required.
