### ISSUE TITLE
Discord mods / in-game mods

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#434]
Limiting the features of what a moderator can do, like only apply 2 week bans for anything but hackers but also opening up 2/3 senior moderator roles that can see and respond to report tickets, apply longer bans if deemed necessary and be a point of call for other moderators rather than them going straight to leadership.

**Comment by JamStonedScones** [comment]
for reference/example a senior mod would need to be both in-game and discord mod to apply and senior mod would oversee both

**Comment by jxckUK** [comment]
I believe at the moment we're not progressing this idea because we believe there is still a need for our oversight whilst moderators settle into the roles and understand the expectations. We've had numerous problems of late with overreaching punishments or lack of investigations leading up to moderation.

Fundamentally we're a game, we want to be moderating as least as possible whilst still ensuring everyone is playing by the rules etc.

As and when this changes the existing moderation team will be informed in #moderator-chat.
