### ISSUE TITLE
[FEAT] Spawning for MPS

### ISSUE THREAD

**Issue by judgegritter** [LondonsBlueLine/tracker#451]
Suggestion for the spawn for Paleto Station to be removed from the options of spawn points under MPS. I don't know anyone that actually wants to spawn up there as the action is mostly in the city or just north of :)

**Comment by judgegritter** [comment]
Alternative option would be manual spawning selection for the station

**Comment by jxckUK** [comment]
Howdy @judgegritter,

Thanks for the feedback, it really helps so keep submitting things.

In the case of spawning, I can understand the frustration, but it is intentional to spread players across the map including Paleto. I know there is currently a workaround which is to "spawn spam" but unfortunately, I'll be patching that soon as it is not intended to be a workable solution.

Donators can select the station in which they'd like to fast travel to using the F5 menu. This was given to donators in spite of our desire to spread you out in response to community feedback. If you'd like to select the station, you spawn at I suggest supporting the server which grants you that bonus as well as some other benefits for supporting the server.
