### ISSUE TITLE
PaDP Car 2

### ISSUE THREAD

**Issue by RI1CAL** [LondonsBlueLine/tracker#468]
Model: https://www.gta5-mods.com/vehicles/west-mercia-police-bmw-x5-e70-arv-els

skin: https://www.gta5-mods.com/paintjobs/diplomatic-protection-group-dpg-bmw-e70

**Comment by RI1CAL** [comment]
https://www.gta5-mods.com/vehicles/2016-met-police-bmw-x5

https://www.gta5-mods.com/paintjobs/bmw-x5-met-police-dpg-arv-skins

If the first doesn't work then i have this one too. If they both dont then i give up

**Comment by CalLBLRP** [comment]
![image](https://user-images.githubusercontent.com/98986766/198308422-63e407aa-b38b-4a3b-b77d-eef555037a58.png)
![image](https://user-images.githubusercontent.com/98986766/198308456-14196aa1-d9a5-4307-82ba-5a3b21c48400.png)
![image](https://user-images.githubusercontent.com/98986766/198308497-8cfd6f48-d54f-4195-9ea8-ac58b499ad10.png)
![image](https://user-images.githubusercontent.com/98986766/198308535-25cbe652-a867-48bc-ad52-edcf21c0202a.png)

Unfortunately, the first link you provided auto fails QC due to the skin. I will now be trying the 2nd link you attached.

**Comment by CalLBLRP** [comment]
Unfortunately it is the same issue with the 2nd link.
