### ISSUE TITLE
[BUG] Fuel Script

### ISSUE THREAD

**Issue by Mighty-Jay** [LondonsBlueLine/tracker#477]
**Describe the bug**
Not all fuel stations are marked within the fuel script to be activated and used to fill vehicles

**To Reproduce**
Very intermittent and when you go to Certain fuel stations, the text to fuel the vehicle does not appear. 
Fuel station on Innocence Bulvard as well as Grove Street are two definite ones that do not work, but all of them do need testing. 

![image](https://user-images.githubusercontent.com/48175432/197878682-d27209db-a2e3-4870-8da9-e4a65dcfee2d.png)

**Comment by jxckUK** [comment]
Yeah we're aware of a few issues with the fuelling system, namely its poor ability to detect vehicles when at or near a pump.

It requires you to go around and place the vehicle in a particular spot. Again, requires some development time to bring this in-house rather than using a base script. That way we can use our prompt system, maybe make it a little more interactive and seamless (eg. animations etc) but again, it's just low down on the priority list.

Another one that is tracked internally on our roadmap (https://github.com/ProjectHyde/ProjectHyde/issues/121).
