### ISSUE TITLE
[FEAT] RTPC announcements channel

### ISSUE THREAD

**Issue by BriannRI1** [LondonsBlueLine/tracker#483]
It would be nice to have a RTPC announcement channel so post important information in there without it getting lost in the chat, 

Also it will be easier for me to post important laws and rules off the roads and any updates within RTPC

**Comment by jxckUK** [comment]
Hi Mate,

We're trying to reduce the number of Discord channels overall so we don't intend to add additional announcement channels for each division which would then hold only a few messages.

I'd seriously recommend using docs.lblrp.com (really, it's a good tool for this kind of information) or requesting us add information or announcements to the website. Otherwise, you can use the pin function in Discord in existing channels for important messages.
