### ISSUE TITLE
Police - Civ arrest interactions 

### ISSUE THREAD

**Issue by JamStonedScones** [LondonsBlueLine/tracker#491]
Would it be possible to add something similar to a QTE (quick time event) when an officer tries to arrest a civ. For example, giving the civ a few seconds to click a certain key bind  to resist or having to keep tapping a key to fill a bar and first one to fill wins?

**Comment by jxckUK** [comment]
Yeah, we can look at this for sure, but it will be something we need to add to the broader roadmap.

It would need to be quite difficult for civilians to achieve and would also need to not be applicable if there is more than one officer stood in your proximity. Because in reality two or more officers aren't going to have trouble putting cuffs on one suspect either by placing them on the ground or against a vehicle etc.

Tracking in https://github.com/ProjectHyde/ProjectHyde/issues/122
