### ISSUE TITLE
Ball for DSU+

### ISSUE THREAD

**Issue by Jjones033** [LondonsBlueLine/tracker#496]
Allow dog units to be equipped with a ball in order for us to be able to play with our dog and reward them when doing something good like searching a vehicle.

**Comment by jxckUK** [comment]
I like the idea, although as the dogs are not "chop" this would actually need to be coded to work. Otherwise, the dog will just stare at you wondering why you're throwing some round thing.

I'll need to move it to the internal roadmap with no ETA (https://github.com/ProjectHyde/ProjectHyde/issues/55).
