### ISSUE TITLE
rockstar

### ISSUE THREAD

**Issue by Harry21313124** [LondonsBlueLine/tracker#590]
### What division were you running as?

content sever

### Describe the Bug

i made a clip on rockstar. i was going to edit and when i clicked the clip crashed i have tried many times and it keeps crashing.

### Expected Behavior

i would expect it to be looked on and try find the problem. 

### To Reproduce

first i made the clip by f1 on the content sever. made 4 clips for a vid. then closed my game and went on the edit clip. started to edit my cilp and i crashed half way

**Comment by CalLBLRP** [comment]
Good Afternoon @Harry21313124,

Can you please provide us a screenshot of your "Performance" menu on TM (Task Manager) in order to review the issue in detail. This could potentially lead to a hardware issue which means that you will need to look at upgrading hardware parts in order for the software to work accordingly.

**Comment by Harry21313124** [comment]
![image](https://user-images.githubusercontent.com/112671213/219436470-94967e18-597c-4e1b-a42d-1dece01a47df.png)

**Comment by CalLBLRP** [comment]
Crash logs will not exactly help us, please read my message before replying.
